### ISSUE TITLE
Can you help me when i click on birthday button it crashes logcat below

### ISSUE THREAD

**Issue by blazingdevil44** [projectworlds32/Age-Calculator-Android#1]
2019-11-20 16:54:03.598 23358-23358/ercanduman.dayofbirth_horoscopes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ercanduman.dayofbirth_horoscopes, PID: 23358
    java.lang.IllegalStateException: Fragment ercanduman.dayofbirth_horoscopes.AgeFragment.DatePickerFragment must be a public static class to be  properly recreated from instance state.
        at android.app.BackStackRecord.doAddOp(BackStackRecord.java:435)
        at android.app.BackStackRecord.add(BackStackRecord.java:415)
        at android.app.DialogFragment.show(DialogFragment.java:229)
        at ercanduman.dayofbirth_horoscopes.AgeFragment.triggerDatePickerDialog(AgeFragment.java:73)
        at ercanduman.dayofbirth_horoscopes.AgeFragment.access$000(AgeFragment.java:20)
        at ercanduman.dayofbirth_horoscopes.AgeFragment$1.onClick(AgeFragment.java:61)
        at android.view.View.performClick(View.java:6329)
        at android.view.View$PerformClick.run(View.java:25002)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
2019-11-20 16:54:03.637 23358-23358/ercanduman.dayofbirth_horoscopes I/Process:

Please help

**Comment by rahul-k-coder** [comment]
Make your age fragment public static  class. i think resolve your issue.
